// Code generated by mockery v2.9.4. DO NOT EDIT.

package accounts

import mock "github.com/stretchr/testify/mock"

// httpClient is an autogenerated mock type for the httpClient type
type mockHttpClient struct {
	mock.Mock
}

// Delete provides a mock function with given fields: resourcePath
func (_m *mockHttpClient) Delete(resourcePath string) error {
	ret := _m.Called(resourcePath)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(resourcePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
