version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - go:
            patterns:
              - "**/*.go"
  govet:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true